
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'FooterNav': typeof import("../components/FooterNav.vue")['default']
    'MenusLayoutNotifications': typeof import("../components/Menus/LayoutNotifications.vue")['default']
    'MenusBlogbar': typeof import("../components/Menus/blogbar.vue")['default']
    'MenusCharacterbar': typeof import("../components/Menus/characterbar.vue")['default']
    'MenusEcosystemmenu': typeof import("../components/Menus/ecosystemmenu.vue")['default']
    'MenusGamebar': typeof import("../components/Menus/gamebar.vue")['default']
    'MenusLowerbar': typeof import("../components/Menus/lowerbar.vue")['default']
    'MenusMonsterbar': typeof import("../components/Menus/monsterbar.vue")['default']
    'MenusMythologybar': typeof import("../components/Menus/mythologybar.vue")['default']
    'MenusStorybar': typeof import("../components/Menus/storybar.vue")['default']
    'RelatedCharacter': typeof import("../components/Related/character.vue")['default']
    'RelatedItem': typeof import("../components/Related/item.vue")['default']
    'RelatedPlace': typeof import("../components/Related/place.vue")['default']
    'RelatedProductCard': typeof import("../components/Related/productCard.vue")['default']
    'RelatedRelatedposts': typeof import("../components/Related/relatedposts.vue")['default']
    'RelatedRelatedproducts': typeof import("../components/Related/relatedproducts.vue")['default']
    'RelatedRelatedstories': typeof import("../components/Related/relatedstories.vue")['default']
    'RelatedStory': typeof import("../components/Related/story.vue")['default']
    'RelatedVideo': typeof import("../components/Related/video.vue")['default']
    'SearchFilters': typeof import("../components/Search/filters.vue")['default']
    'SearchResultsBooksSearch': typeof import("../components/Search/results/booksSearch.vue")['default']
    'SearchResultsFinanceSearch': typeof import("../components/Search/results/financeSearch.vue")['default']
    'SearchResultsImageSearch': typeof import("../components/Search/results/imageSearch.vue")['default']
    'SearchResultsMusicSearch': typeof import("../components/Search/results/musicSearch.vue")['default']
    'SearchResultsNewsSearch': typeof import("../components/Search/results/newsSearch.vue")['default']
    'SearchResultsSpaceSearch': typeof import("../components/Search/results/spaceSearch.vue")['default']
    'SearchResultsTravelSearch': typeof import("../components/Search/results/travelSearch.vue")['default']
    'SearchResultsVideoSearch': typeof import("../components/Search/results/videoSearch.vue")['default']
    'Search': typeof import("../components/Search/search.vue")['default']
    'SearchWidgetsClearRefinements': typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
    'SearchWidgetsNoResults': typeof import("../components/Search/widgets/NoResults.vue")['default']
    'AuthenticationLogout': typeof import("../components/authentication/logout.vue")['default']
    'HomePageCharacters': typeof import("../components/homePage/characters.vue")['default']
    'HomePageContentSection': typeof import("../components/homePage/contentSection.vue")['default']
    'HomePageIntro': typeof import("../components/homePage/intro.vue")['default']
    'HomePageMultiversebanner': typeof import("../components/homePage/multiversebanner.vue")['default']
    'HomePageVideoSection': typeof import("../components/homePage/videoSection.vue")['default']
    'MediaAudioPlayer': typeof import("../components/media/audio/audioPlayer.vue")['default']
    'MediaLivePlayer': typeof import("../components/media/live/livePlayer.vue")['default']
    'MediaVideoVideojs': typeof import("../components/media/video/videojs.vue")['default']
    'PagesAliens': typeof import("../components/pages/aliens.vue")['default']
    'PagesAngels': typeof import("../components/pages/angels.vue")['default']
    'PagesDemons': typeof import("../components/pages/demons.vue")['default']
    'PagesHumans': typeof import("../components/pages/humans.vue")['default']
    'PagesItems': typeof import("../components/pages/items.vue")['default']
    'PagesLevels': typeof import("../components/pages/levels.vue")['default']
    'PagesMythicalcreatures': typeof import("../components/pages/mythicalcreatures.vue")['default']
    'PagesOthermyths': typeof import("../components/pages/othermyths.vue")['default']
    'PagesPlaces': typeof import("../components/pages/places.vue")['default']
    'PagesTypes': typeof import("../components/pages/types.vue")['default']
    'PartialsAddtolist': typeof import("../components/partials/addtolist.vue")['default']
    'PartialsComments': typeof import("../components/partials/comments.vue")['default']
    'PartialsCreateListBtn': typeof import("../components/partials/createListBtn.vue")['default']
    'PartialsFollowButton': typeof import("../components/partials/followButton.vue")['default']
    'PartialsListBtn': typeof import("../components/partials/listBtn.vue")['default']
    'PartialsShare': typeof import("../components/partials/share.vue")['default']
    'PartialsShareDialog': typeof import("../components/partials/shareDialog.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'SfAccordionItem': typeof import("@storefront-ui/vue")['SfAccordionItem']
    'SfBadge': typeof import("@storefront-ui/vue")['SfBadge']
    'SfButton': typeof import("@storefront-ui/vue")['SfButton']
    'SfCheckbox': typeof import("@storefront-ui/vue")['SfCheckbox']
    'SfChip': typeof import("@storefront-ui/vue")['SfChip']
    'SfCounter': typeof import("@storefront-ui/vue")['SfCounter']
    'SfDrawer': typeof import("@storefront-ui/vue")['SfDrawer']
    'SfDropdown': typeof import("@storefront-ui/vue")['SfDropdown']
    'SfIconAdd': typeof import("@storefront-ui/vue")['SfIconAdd']
    'SfIconAddShoppingCart': typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
    'SfIconAlokai': typeof import("@storefront-ui/vue")['SfIconAlokai']
    'SfIconAlokaiFull': typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
    'SfIconArrowBack': typeof import("@storefront-ui/vue")['SfIconArrowBack']
    'SfIconArrowDownward': typeof import("@storefront-ui/vue")['SfIconArrowDownward']
    'SfIconArrowForward': typeof import("@storefront-ui/vue")['SfIconArrowForward']
    'SfIconArrowUpward': typeof import("@storefront-ui/vue")['SfIconArrowUpward']
    'SfIconBase': typeof import("@storefront-ui/vue")['SfIconBase']
    'SfIconBlock': typeof import("@storefront-ui/vue")['SfIconBlock']
    'SfIconCalendarToday': typeof import("@storefront-ui/vue")['SfIconCalendarToday']
    'SfIconCall': typeof import("@storefront-ui/vue")['SfIconCall']
    'SfIconCancel': typeof import("@storefront-ui/vue")['SfIconCancel']
    'SfIconCheck': typeof import("@storefront-ui/vue")['SfIconCheck']
    'SfIconCheckBox': typeof import("@storefront-ui/vue")['SfIconCheckBox']
    'SfIconCheckBoxOutlineBlank': typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
    'SfIconCheckCircle': typeof import("@storefront-ui/vue")['SfIconCheckCircle']
    'SfIconChevronLeft': typeof import("@storefront-ui/vue")['SfIconChevronLeft']
    'SfIconChevronRight': typeof import("@storefront-ui/vue")['SfIconChevronRight']
    'SfIconCircle': typeof import("@storefront-ui/vue")['SfIconCircle']
    'SfIconClose': typeof import("@storefront-ui/vue")['SfIconClose']
    'SfIconCloseSm': typeof import("@storefront-ui/vue")['SfIconCloseSm']
    'SfIconCompareArrows': typeof import("@storefront-ui/vue")['SfIconCompareArrows']
    'SfIconContactSupport': typeof import("@storefront-ui/vue")['SfIconContactSupport']
    'SfIconCreditCard': typeof import("@storefront-ui/vue")['SfIconCreditCard']
    'SfIconDelete': typeof import("@storefront-ui/vue")['SfIconDelete']
    'SfIconDownload': typeof import("@storefront-ui/vue")['SfIconDownload']
    'SfIconEmail': typeof import("@storefront-ui/vue")['SfIconEmail']
    'SfIconError': typeof import("@storefront-ui/vue")['SfIconError']
    'SfIconExpandLess': typeof import("@storefront-ui/vue")['SfIconExpandLess']
    'SfIconExpandMore': typeof import("@storefront-ui/vue")['SfIconExpandMore']
    'SfIconFacebook': typeof import("@storefront-ui/vue")['SfIconFacebook']
    'SfIconFavorite': typeof import("@storefront-ui/vue")['SfIconFavorite']
    'SfIconFavoriteFilled': typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
    'SfIconGridView': typeof import("@storefront-ui/vue")['SfIconGridView']
    'SfIconHelp': typeof import("@storefront-ui/vue")['SfIconHelp']
    'SfIconHome': typeof import("@storefront-ui/vue")['SfIconHome']
    'SfIconIndeterminateCheckBox': typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
    'SfIconInfo': typeof import("@storefront-ui/vue")['SfIconInfo']
    'SfIconInstagram': typeof import("@storefront-ui/vue")['SfIconInstagram']
    'SfIconLanguage': typeof import("@storefront-ui/vue")['SfIconLanguage']
    'SfIconLocalShipping': typeof import("@storefront-ui/vue")['SfIconLocalShipping']
    'SfIconLocalFireDepartment': typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
    'SfIconLocationOn': typeof import("@storefront-ui/vue")['SfIconLocationOn']
    'SfIconLocationOnFilled': typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
    'SfIconLock': typeof import("@storefront-ui/vue")['SfIconLock']
    'SfIconLockOpen': typeof import("@storefront-ui/vue")['SfIconLockOpen']
    'SfIconLogin': typeof import("@storefront-ui/vue")['SfIconLogin']
    'SfIconLogout': typeof import("@storefront-ui/vue")['SfIconLogout']
    'SfIconMenu': typeof import("@storefront-ui/vue")['SfIconMenu']
    'SfIconMoreHoriz': typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
    'SfIconMoreVert': typeof import("@storefront-ui/vue")['SfIconMoreVert']
    'SfIconOpenInNew': typeof import("@storefront-ui/vue")['SfIconOpenInNew']
    'SfIconOpenSource': typeof import("@storefront-ui/vue")['SfIconOpenSource']
    'SfIconPackage': typeof import("@storefront-ui/vue")['SfIconPackage']
    'SfIconPercent': typeof import("@storefront-ui/vue")['SfIconPercent']
    'SfIconPerson': typeof import("@storefront-ui/vue")['SfIconPerson']
    'SfIconPinterest': typeof import("@storefront-ui/vue")['SfIconPinterest']
    'SfIconPublishedWithChanges': typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
    'SfIconRadioButtonChecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
    'SfIconRadioButtonUnchecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
    'SfIconReact': typeof import("@storefront-ui/vue")['SfIconReact']
    'SfIconRemove': typeof import("@storefront-ui/vue")['SfIconRemove']
    'SfIconRemoveShoppingCart': typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
    'SfIconSafetyCheck': typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
    'SfIconSchedule': typeof import("@storefront-ui/vue")['SfIconSchedule']
    'SfIconSearch': typeof import("@storefront-ui/vue")['SfIconSearch']
    'SfIconSell': typeof import("@storefront-ui/vue")['SfIconSell']
    'SfIconShare': typeof import("@storefront-ui/vue")['SfIconShare']
    'SfIconShoppingCart': typeof import("@storefront-ui/vue")['SfIconShoppingCart']
    'SfIconShoppingCartCheckout': typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
    'SfIconSort': typeof import("@storefront-ui/vue")['SfIconSort']
    'SfIconStar': typeof import("@storefront-ui/vue")['SfIconStar']
    'SfIconStarFilled': typeof import("@storefront-ui/vue")['SfIconStarFilled']
    'SfIconStarHalf': typeof import("@storefront-ui/vue")['SfIconStarHalf']
    'SfIconThumbDown': typeof import("@storefront-ui/vue")['SfIconThumbDown']
    'SfIconThumbUp': typeof import("@storefront-ui/vue")['SfIconThumbUp']
    'SfIconTune': typeof import("@storefront-ui/vue")['SfIconTune']
    'SfIconTwitter': typeof import("@storefront-ui/vue")['SfIconTwitter']
    'SfIconUndo': typeof import("@storefront-ui/vue")['SfIconUndo']
    'SfIconUnfoldMore': typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
    'SfIconUpload': typeof import("@storefront-ui/vue")['SfIconUpload']
    'SfIconViewList': typeof import("@storefront-ui/vue")['SfIconViewList']
    'SfIconVisibility': typeof import("@storefront-ui/vue")['SfIconVisibility']
    'SfIconVisibilityOff': typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
    'SfIconVsfDiamond': typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
    'SfIconVuejs': typeof import("@storefront-ui/vue")['SfIconVuejs']
    'SfIconVuestorefront': typeof import("@storefront-ui/vue")['SfIconVuestorefront']
    'SfIconWarehouse': typeof import("@storefront-ui/vue")['SfIconWarehouse']
    'SfIconWarning': typeof import("@storefront-ui/vue")['SfIconWarning']
    'SfIconYoutube': typeof import("@storefront-ui/vue")['SfIconYoutube']
    'SfInput': typeof import("@storefront-ui/vue")['SfInput']
    'SfLink': typeof import("@storefront-ui/vue")['SfLink']
    'SfListItem': typeof import("@storefront-ui/vue")['SfListItem']
    'SfLoaderCircular': typeof import("@storefront-ui/vue")['SfLoaderCircular']
    'SfLoaderLinear': typeof import("@storefront-ui/vue")['SfLoaderLinear']
    'SfModal': typeof import("@storefront-ui/vue")['SfModal']
    'SfProgressCircular': typeof import("@storefront-ui/vue")['SfProgressCircular']
    'SfProgressLinear': typeof import("@storefront-ui/vue")['SfProgressLinear']
    'SfRadio': typeof import("@storefront-ui/vue")['SfRadio']
    'SfRating': typeof import("@storefront-ui/vue")['SfRating']
    'SfRatingButton': typeof import("@storefront-ui/vue")['SfRatingButton']
    'SfScrollable': typeof import("@storefront-ui/vue")['SfScrollable']
    'SfSelect': typeof import("@storefront-ui/vue")['SfSelect']
    'SfSwitch': typeof import("@storefront-ui/vue")['SfSwitch']
    'SfTextarea': typeof import("@storefront-ui/vue")['SfTextarea']
    'SfThumbnail': typeof import("@storefront-ui/vue")['SfThumbnail']
    'SfTooltip': typeof import("@storefront-ui/vue")['SfTooltip']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyFooterNav': typeof import("../components/FooterNav.vue")['default']
    'LazyMenusLayoutNotifications': typeof import("../components/Menus/LayoutNotifications.vue")['default']
    'LazyMenusBlogbar': typeof import("../components/Menus/blogbar.vue")['default']
    'LazyMenusCharacterbar': typeof import("../components/Menus/characterbar.vue")['default']
    'LazyMenusEcosystemmenu': typeof import("../components/Menus/ecosystemmenu.vue")['default']
    'LazyMenusGamebar': typeof import("../components/Menus/gamebar.vue")['default']
    'LazyMenusLowerbar': typeof import("../components/Menus/lowerbar.vue")['default']
    'LazyMenusMonsterbar': typeof import("../components/Menus/monsterbar.vue")['default']
    'LazyMenusMythologybar': typeof import("../components/Menus/mythologybar.vue")['default']
    'LazyMenusStorybar': typeof import("../components/Menus/storybar.vue")['default']
    'LazyRelatedCharacter': typeof import("../components/Related/character.vue")['default']
    'LazyRelatedItem': typeof import("../components/Related/item.vue")['default']
    'LazyRelatedPlace': typeof import("../components/Related/place.vue")['default']
    'LazyRelatedProductCard': typeof import("../components/Related/productCard.vue")['default']
    'LazyRelatedRelatedposts': typeof import("../components/Related/relatedposts.vue")['default']
    'LazyRelatedRelatedproducts': typeof import("../components/Related/relatedproducts.vue")['default']
    'LazyRelatedRelatedstories': typeof import("../components/Related/relatedstories.vue")['default']
    'LazyRelatedStory': typeof import("../components/Related/story.vue")['default']
    'LazyRelatedVideo': typeof import("../components/Related/video.vue")['default']
    'LazySearchFilters': typeof import("../components/Search/filters.vue")['default']
    'LazySearchResultsBooksSearch': typeof import("../components/Search/results/booksSearch.vue")['default']
    'LazySearchResultsFinanceSearch': typeof import("../components/Search/results/financeSearch.vue")['default']
    'LazySearchResultsImageSearch': typeof import("../components/Search/results/imageSearch.vue")['default']
    'LazySearchResultsMusicSearch': typeof import("../components/Search/results/musicSearch.vue")['default']
    'LazySearchResultsNewsSearch': typeof import("../components/Search/results/newsSearch.vue")['default']
    'LazySearchResultsSpaceSearch': typeof import("../components/Search/results/spaceSearch.vue")['default']
    'LazySearchResultsTravelSearch': typeof import("../components/Search/results/travelSearch.vue")['default']
    'LazySearchResultsVideoSearch': typeof import("../components/Search/results/videoSearch.vue")['default']
    'LazySearch': typeof import("../components/Search/search.vue")['default']
    'LazySearchWidgetsClearRefinements': typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
    'LazySearchWidgetsNoResults': typeof import("../components/Search/widgets/NoResults.vue")['default']
    'LazyAuthenticationLogout': typeof import("../components/authentication/logout.vue")['default']
    'LazyHomePageCharacters': typeof import("../components/homePage/characters.vue")['default']
    'LazyHomePageContentSection': typeof import("../components/homePage/contentSection.vue")['default']
    'LazyHomePageIntro': typeof import("../components/homePage/intro.vue")['default']
    'LazyHomePageMultiversebanner': typeof import("../components/homePage/multiversebanner.vue")['default']
    'LazyHomePageVideoSection': typeof import("../components/homePage/videoSection.vue")['default']
    'LazyMediaAudioPlayer': typeof import("../components/media/audio/audioPlayer.vue")['default']
    'LazyMediaLivePlayer': typeof import("../components/media/live/livePlayer.vue")['default']
    'LazyMediaVideoVideojs': typeof import("../components/media/video/videojs.vue")['default']
    'LazyPagesAliens': typeof import("../components/pages/aliens.vue")['default']
    'LazyPagesAngels': typeof import("../components/pages/angels.vue")['default']
    'LazyPagesDemons': typeof import("../components/pages/demons.vue")['default']
    'LazyPagesHumans': typeof import("../components/pages/humans.vue")['default']
    'LazyPagesItems': typeof import("../components/pages/items.vue")['default']
    'LazyPagesLevels': typeof import("../components/pages/levels.vue")['default']
    'LazyPagesMythicalcreatures': typeof import("../components/pages/mythicalcreatures.vue")['default']
    'LazyPagesOthermyths': typeof import("../components/pages/othermyths.vue")['default']
    'LazyPagesPlaces': typeof import("../components/pages/places.vue")['default']
    'LazyPagesTypes': typeof import("../components/pages/types.vue")['default']
    'LazyPartialsAddtolist': typeof import("../components/partials/addtolist.vue")['default']
    'LazyPartialsComments': typeof import("../components/partials/comments.vue")['default']
    'LazyPartialsCreateListBtn': typeof import("../components/partials/createListBtn.vue")['default']
    'LazyPartialsFollowButton': typeof import("../components/partials/followButton.vue")['default']
    'LazyPartialsListBtn': typeof import("../components/partials/listBtn.vue")['default']
    'LazyPartialsShare': typeof import("../components/partials/share.vue")['default']
    'LazyPartialsShareDialog': typeof import("../components/partials/shareDialog.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazySfAccordionItem': typeof import("@storefront-ui/vue")['SfAccordionItem']
    'LazySfBadge': typeof import("@storefront-ui/vue")['SfBadge']
    'LazySfButton': typeof import("@storefront-ui/vue")['SfButton']
    'LazySfCheckbox': typeof import("@storefront-ui/vue")['SfCheckbox']
    'LazySfChip': typeof import("@storefront-ui/vue")['SfChip']
    'LazySfCounter': typeof import("@storefront-ui/vue")['SfCounter']
    'LazySfDrawer': typeof import("@storefront-ui/vue")['SfDrawer']
    'LazySfDropdown': typeof import("@storefront-ui/vue")['SfDropdown']
    'LazySfIconAdd': typeof import("@storefront-ui/vue")['SfIconAdd']
    'LazySfIconAddShoppingCart': typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
    'LazySfIconAlokai': typeof import("@storefront-ui/vue")['SfIconAlokai']
    'LazySfIconAlokaiFull': typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
    'LazySfIconArrowBack': typeof import("@storefront-ui/vue")['SfIconArrowBack']
    'LazySfIconArrowDownward': typeof import("@storefront-ui/vue")['SfIconArrowDownward']
    'LazySfIconArrowForward': typeof import("@storefront-ui/vue")['SfIconArrowForward']
    'LazySfIconArrowUpward': typeof import("@storefront-ui/vue")['SfIconArrowUpward']
    'LazySfIconBase': typeof import("@storefront-ui/vue")['SfIconBase']
    'LazySfIconBlock': typeof import("@storefront-ui/vue")['SfIconBlock']
    'LazySfIconCalendarToday': typeof import("@storefront-ui/vue")['SfIconCalendarToday']
    'LazySfIconCall': typeof import("@storefront-ui/vue")['SfIconCall']
    'LazySfIconCancel': typeof import("@storefront-ui/vue")['SfIconCancel']
    'LazySfIconCheck': typeof import("@storefront-ui/vue")['SfIconCheck']
    'LazySfIconCheckBox': typeof import("@storefront-ui/vue")['SfIconCheckBox']
    'LazySfIconCheckBoxOutlineBlank': typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
    'LazySfIconCheckCircle': typeof import("@storefront-ui/vue")['SfIconCheckCircle']
    'LazySfIconChevronLeft': typeof import("@storefront-ui/vue")['SfIconChevronLeft']
    'LazySfIconChevronRight': typeof import("@storefront-ui/vue")['SfIconChevronRight']
    'LazySfIconCircle': typeof import("@storefront-ui/vue")['SfIconCircle']
    'LazySfIconClose': typeof import("@storefront-ui/vue")['SfIconClose']
    'LazySfIconCloseSm': typeof import("@storefront-ui/vue")['SfIconCloseSm']
    'LazySfIconCompareArrows': typeof import("@storefront-ui/vue")['SfIconCompareArrows']
    'LazySfIconContactSupport': typeof import("@storefront-ui/vue")['SfIconContactSupport']
    'LazySfIconCreditCard': typeof import("@storefront-ui/vue")['SfIconCreditCard']
    'LazySfIconDelete': typeof import("@storefront-ui/vue")['SfIconDelete']
    'LazySfIconDownload': typeof import("@storefront-ui/vue")['SfIconDownload']
    'LazySfIconEmail': typeof import("@storefront-ui/vue")['SfIconEmail']
    'LazySfIconError': typeof import("@storefront-ui/vue")['SfIconError']
    'LazySfIconExpandLess': typeof import("@storefront-ui/vue")['SfIconExpandLess']
    'LazySfIconExpandMore': typeof import("@storefront-ui/vue")['SfIconExpandMore']
    'LazySfIconFacebook': typeof import("@storefront-ui/vue")['SfIconFacebook']
    'LazySfIconFavorite': typeof import("@storefront-ui/vue")['SfIconFavorite']
    'LazySfIconFavoriteFilled': typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
    'LazySfIconGridView': typeof import("@storefront-ui/vue")['SfIconGridView']
    'LazySfIconHelp': typeof import("@storefront-ui/vue")['SfIconHelp']
    'LazySfIconHome': typeof import("@storefront-ui/vue")['SfIconHome']
    'LazySfIconIndeterminateCheckBox': typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
    'LazySfIconInfo': typeof import("@storefront-ui/vue")['SfIconInfo']
    'LazySfIconInstagram': typeof import("@storefront-ui/vue")['SfIconInstagram']
    'LazySfIconLanguage': typeof import("@storefront-ui/vue")['SfIconLanguage']
    'LazySfIconLocalShipping': typeof import("@storefront-ui/vue")['SfIconLocalShipping']
    'LazySfIconLocalFireDepartment': typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
    'LazySfIconLocationOn': typeof import("@storefront-ui/vue")['SfIconLocationOn']
    'LazySfIconLocationOnFilled': typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
    'LazySfIconLock': typeof import("@storefront-ui/vue")['SfIconLock']
    'LazySfIconLockOpen': typeof import("@storefront-ui/vue")['SfIconLockOpen']
    'LazySfIconLogin': typeof import("@storefront-ui/vue")['SfIconLogin']
    'LazySfIconLogout': typeof import("@storefront-ui/vue")['SfIconLogout']
    'LazySfIconMenu': typeof import("@storefront-ui/vue")['SfIconMenu']
    'LazySfIconMoreHoriz': typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
    'LazySfIconMoreVert': typeof import("@storefront-ui/vue")['SfIconMoreVert']
    'LazySfIconOpenInNew': typeof import("@storefront-ui/vue")['SfIconOpenInNew']
    'LazySfIconOpenSource': typeof import("@storefront-ui/vue")['SfIconOpenSource']
    'LazySfIconPackage': typeof import("@storefront-ui/vue")['SfIconPackage']
    'LazySfIconPercent': typeof import("@storefront-ui/vue")['SfIconPercent']
    'LazySfIconPerson': typeof import("@storefront-ui/vue")['SfIconPerson']
    'LazySfIconPinterest': typeof import("@storefront-ui/vue")['SfIconPinterest']
    'LazySfIconPublishedWithChanges': typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
    'LazySfIconRadioButtonChecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
    'LazySfIconRadioButtonUnchecked': typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
    'LazySfIconReact': typeof import("@storefront-ui/vue")['SfIconReact']
    'LazySfIconRemove': typeof import("@storefront-ui/vue")['SfIconRemove']
    'LazySfIconRemoveShoppingCart': typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
    'LazySfIconSafetyCheck': typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
    'LazySfIconSchedule': typeof import("@storefront-ui/vue")['SfIconSchedule']
    'LazySfIconSearch': typeof import("@storefront-ui/vue")['SfIconSearch']
    'LazySfIconSell': typeof import("@storefront-ui/vue")['SfIconSell']
    'LazySfIconShare': typeof import("@storefront-ui/vue")['SfIconShare']
    'LazySfIconShoppingCart': typeof import("@storefront-ui/vue")['SfIconShoppingCart']
    'LazySfIconShoppingCartCheckout': typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
    'LazySfIconSort': typeof import("@storefront-ui/vue")['SfIconSort']
    'LazySfIconStar': typeof import("@storefront-ui/vue")['SfIconStar']
    'LazySfIconStarFilled': typeof import("@storefront-ui/vue")['SfIconStarFilled']
    'LazySfIconStarHalf': typeof import("@storefront-ui/vue")['SfIconStarHalf']
    'LazySfIconThumbDown': typeof import("@storefront-ui/vue")['SfIconThumbDown']
    'LazySfIconThumbUp': typeof import("@storefront-ui/vue")['SfIconThumbUp']
    'LazySfIconTune': typeof import("@storefront-ui/vue")['SfIconTune']
    'LazySfIconTwitter': typeof import("@storefront-ui/vue")['SfIconTwitter']
    'LazySfIconUndo': typeof import("@storefront-ui/vue")['SfIconUndo']
    'LazySfIconUnfoldMore': typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
    'LazySfIconUpload': typeof import("@storefront-ui/vue")['SfIconUpload']
    'LazySfIconViewList': typeof import("@storefront-ui/vue")['SfIconViewList']
    'LazySfIconVisibility': typeof import("@storefront-ui/vue")['SfIconVisibility']
    'LazySfIconVisibilityOff': typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
    'LazySfIconVsfDiamond': typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
    'LazySfIconVuejs': typeof import("@storefront-ui/vue")['SfIconVuejs']
    'LazySfIconVuestorefront': typeof import("@storefront-ui/vue")['SfIconVuestorefront']
    'LazySfIconWarehouse': typeof import("@storefront-ui/vue")['SfIconWarehouse']
    'LazySfIconWarning': typeof import("@storefront-ui/vue")['SfIconWarning']
    'LazySfIconYoutube': typeof import("@storefront-ui/vue")['SfIconYoutube']
    'LazySfInput': typeof import("@storefront-ui/vue")['SfInput']
    'LazySfLink': typeof import("@storefront-ui/vue")['SfLink']
    'LazySfListItem': typeof import("@storefront-ui/vue")['SfListItem']
    'LazySfLoaderCircular': typeof import("@storefront-ui/vue")['SfLoaderCircular']
    'LazySfLoaderLinear': typeof import("@storefront-ui/vue")['SfLoaderLinear']
    'LazySfModal': typeof import("@storefront-ui/vue")['SfModal']
    'LazySfProgressCircular': typeof import("@storefront-ui/vue")['SfProgressCircular']
    'LazySfProgressLinear': typeof import("@storefront-ui/vue")['SfProgressLinear']
    'LazySfRadio': typeof import("@storefront-ui/vue")['SfRadio']
    'LazySfRating': typeof import("@storefront-ui/vue")['SfRating']
    'LazySfRatingButton': typeof import("@storefront-ui/vue")['SfRatingButton']
    'LazySfScrollable': typeof import("@storefront-ui/vue")['SfScrollable']
    'LazySfSelect': typeof import("@storefront-ui/vue")['SfSelect']
    'LazySfSwitch': typeof import("@storefront-ui/vue")['SfSwitch']
    'LazySfTextarea': typeof import("@storefront-ui/vue")['SfTextarea']
    'LazySfThumbnail': typeof import("@storefront-ui/vue")['SfThumbnail']
    'LazySfTooltip': typeof import("@storefront-ui/vue")['SfTooltip']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const FooterNav: typeof import("../components/FooterNav.vue")['default']
export const MenusLayoutNotifications: typeof import("../components/Menus/LayoutNotifications.vue")['default']
export const MenusBlogbar: typeof import("../components/Menus/blogbar.vue")['default']
export const MenusCharacterbar: typeof import("../components/Menus/characterbar.vue")['default']
export const MenusEcosystemmenu: typeof import("../components/Menus/ecosystemmenu.vue")['default']
export const MenusGamebar: typeof import("../components/Menus/gamebar.vue")['default']
export const MenusLowerbar: typeof import("../components/Menus/lowerbar.vue")['default']
export const MenusMonsterbar: typeof import("../components/Menus/monsterbar.vue")['default']
export const MenusMythologybar: typeof import("../components/Menus/mythologybar.vue")['default']
export const MenusStorybar: typeof import("../components/Menus/storybar.vue")['default']
export const RelatedCharacter: typeof import("../components/Related/character.vue")['default']
export const RelatedItem: typeof import("../components/Related/item.vue")['default']
export const RelatedPlace: typeof import("../components/Related/place.vue")['default']
export const RelatedProductCard: typeof import("../components/Related/productCard.vue")['default']
export const RelatedRelatedposts: typeof import("../components/Related/relatedposts.vue")['default']
export const RelatedRelatedproducts: typeof import("../components/Related/relatedproducts.vue")['default']
export const RelatedRelatedstories: typeof import("../components/Related/relatedstories.vue")['default']
export const RelatedStory: typeof import("../components/Related/story.vue")['default']
export const RelatedVideo: typeof import("../components/Related/video.vue")['default']
export const SearchFilters: typeof import("../components/Search/filters.vue")['default']
export const SearchResultsBooksSearch: typeof import("../components/Search/results/booksSearch.vue")['default']
export const SearchResultsFinanceSearch: typeof import("../components/Search/results/financeSearch.vue")['default']
export const SearchResultsImageSearch: typeof import("../components/Search/results/imageSearch.vue")['default']
export const SearchResultsMusicSearch: typeof import("../components/Search/results/musicSearch.vue")['default']
export const SearchResultsNewsSearch: typeof import("../components/Search/results/newsSearch.vue")['default']
export const SearchResultsSpaceSearch: typeof import("../components/Search/results/spaceSearch.vue")['default']
export const SearchResultsTravelSearch: typeof import("../components/Search/results/travelSearch.vue")['default']
export const SearchResultsVideoSearch: typeof import("../components/Search/results/videoSearch.vue")['default']
export const Search: typeof import("../components/Search/search.vue")['default']
export const SearchWidgetsClearRefinements: typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
export const SearchWidgetsNoResults: typeof import("../components/Search/widgets/NoResults.vue")['default']
export const AuthenticationLogout: typeof import("../components/authentication/logout.vue")['default']
export const HomePageCharacters: typeof import("../components/homePage/characters.vue")['default']
export const HomePageContentSection: typeof import("../components/homePage/contentSection.vue")['default']
export const HomePageIntro: typeof import("../components/homePage/intro.vue")['default']
export const HomePageMultiversebanner: typeof import("../components/homePage/multiversebanner.vue")['default']
export const HomePageVideoSection: typeof import("../components/homePage/videoSection.vue")['default']
export const MediaAudioPlayer: typeof import("../components/media/audio/audioPlayer.vue")['default']
export const MediaLivePlayer: typeof import("../components/media/live/livePlayer.vue")['default']
export const MediaVideoVideojs: typeof import("../components/media/video/videojs.vue")['default']
export const PagesAliens: typeof import("../components/pages/aliens.vue")['default']
export const PagesAngels: typeof import("../components/pages/angels.vue")['default']
export const PagesDemons: typeof import("../components/pages/demons.vue")['default']
export const PagesHumans: typeof import("../components/pages/humans.vue")['default']
export const PagesItems: typeof import("../components/pages/items.vue")['default']
export const PagesLevels: typeof import("../components/pages/levels.vue")['default']
export const PagesMythicalcreatures: typeof import("../components/pages/mythicalcreatures.vue")['default']
export const PagesOthermyths: typeof import("../components/pages/othermyths.vue")['default']
export const PagesPlaces: typeof import("../components/pages/places.vue")['default']
export const PagesTypes: typeof import("../components/pages/types.vue")['default']
export const PartialsAddtolist: typeof import("../components/partials/addtolist.vue")['default']
export const PartialsComments: typeof import("../components/partials/comments.vue")['default']
export const PartialsCreateListBtn: typeof import("../components/partials/createListBtn.vue")['default']
export const PartialsFollowButton: typeof import("../components/partials/followButton.vue")['default']
export const PartialsListBtn: typeof import("../components/partials/listBtn.vue")['default']
export const PartialsShare: typeof import("../components/partials/share.vue")['default']
export const PartialsShareDialog: typeof import("../components/partials/shareDialog.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const SfAccordionItem: typeof import("@storefront-ui/vue")['SfAccordionItem']
export const SfBadge: typeof import("@storefront-ui/vue")['SfBadge']
export const SfButton: typeof import("@storefront-ui/vue")['SfButton']
export const SfCheckbox: typeof import("@storefront-ui/vue")['SfCheckbox']
export const SfChip: typeof import("@storefront-ui/vue")['SfChip']
export const SfCounter: typeof import("@storefront-ui/vue")['SfCounter']
export const SfDrawer: typeof import("@storefront-ui/vue")['SfDrawer']
export const SfDropdown: typeof import("@storefront-ui/vue")['SfDropdown']
export const SfIconAdd: typeof import("@storefront-ui/vue")['SfIconAdd']
export const SfIconAddShoppingCart: typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
export const SfIconAlokai: typeof import("@storefront-ui/vue")['SfIconAlokai']
export const SfIconAlokaiFull: typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
export const SfIconArrowBack: typeof import("@storefront-ui/vue")['SfIconArrowBack']
export const SfIconArrowDownward: typeof import("@storefront-ui/vue")['SfIconArrowDownward']
export const SfIconArrowForward: typeof import("@storefront-ui/vue")['SfIconArrowForward']
export const SfIconArrowUpward: typeof import("@storefront-ui/vue")['SfIconArrowUpward']
export const SfIconBase: typeof import("@storefront-ui/vue")['SfIconBase']
export const SfIconBlock: typeof import("@storefront-ui/vue")['SfIconBlock']
export const SfIconCalendarToday: typeof import("@storefront-ui/vue")['SfIconCalendarToday']
export const SfIconCall: typeof import("@storefront-ui/vue")['SfIconCall']
export const SfIconCancel: typeof import("@storefront-ui/vue")['SfIconCancel']
export const SfIconCheck: typeof import("@storefront-ui/vue")['SfIconCheck']
export const SfIconCheckBox: typeof import("@storefront-ui/vue")['SfIconCheckBox']
export const SfIconCheckBoxOutlineBlank: typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
export const SfIconCheckCircle: typeof import("@storefront-ui/vue")['SfIconCheckCircle']
export const SfIconChevronLeft: typeof import("@storefront-ui/vue")['SfIconChevronLeft']
export const SfIconChevronRight: typeof import("@storefront-ui/vue")['SfIconChevronRight']
export const SfIconCircle: typeof import("@storefront-ui/vue")['SfIconCircle']
export const SfIconClose: typeof import("@storefront-ui/vue")['SfIconClose']
export const SfIconCloseSm: typeof import("@storefront-ui/vue")['SfIconCloseSm']
export const SfIconCompareArrows: typeof import("@storefront-ui/vue")['SfIconCompareArrows']
export const SfIconContactSupport: typeof import("@storefront-ui/vue")['SfIconContactSupport']
export const SfIconCreditCard: typeof import("@storefront-ui/vue")['SfIconCreditCard']
export const SfIconDelete: typeof import("@storefront-ui/vue")['SfIconDelete']
export const SfIconDownload: typeof import("@storefront-ui/vue")['SfIconDownload']
export const SfIconEmail: typeof import("@storefront-ui/vue")['SfIconEmail']
export const SfIconError: typeof import("@storefront-ui/vue")['SfIconError']
export const SfIconExpandLess: typeof import("@storefront-ui/vue")['SfIconExpandLess']
export const SfIconExpandMore: typeof import("@storefront-ui/vue")['SfIconExpandMore']
export const SfIconFacebook: typeof import("@storefront-ui/vue")['SfIconFacebook']
export const SfIconFavorite: typeof import("@storefront-ui/vue")['SfIconFavorite']
export const SfIconFavoriteFilled: typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
export const SfIconGridView: typeof import("@storefront-ui/vue")['SfIconGridView']
export const SfIconHelp: typeof import("@storefront-ui/vue")['SfIconHelp']
export const SfIconHome: typeof import("@storefront-ui/vue")['SfIconHome']
export const SfIconIndeterminateCheckBox: typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
export const SfIconInfo: typeof import("@storefront-ui/vue")['SfIconInfo']
export const SfIconInstagram: typeof import("@storefront-ui/vue")['SfIconInstagram']
export const SfIconLanguage: typeof import("@storefront-ui/vue")['SfIconLanguage']
export const SfIconLocalShipping: typeof import("@storefront-ui/vue")['SfIconLocalShipping']
export const SfIconLocalFireDepartment: typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
export const SfIconLocationOn: typeof import("@storefront-ui/vue")['SfIconLocationOn']
export const SfIconLocationOnFilled: typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
export const SfIconLock: typeof import("@storefront-ui/vue")['SfIconLock']
export const SfIconLockOpen: typeof import("@storefront-ui/vue")['SfIconLockOpen']
export const SfIconLogin: typeof import("@storefront-ui/vue")['SfIconLogin']
export const SfIconLogout: typeof import("@storefront-ui/vue")['SfIconLogout']
export const SfIconMenu: typeof import("@storefront-ui/vue")['SfIconMenu']
export const SfIconMoreHoriz: typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
export const SfIconMoreVert: typeof import("@storefront-ui/vue")['SfIconMoreVert']
export const SfIconOpenInNew: typeof import("@storefront-ui/vue")['SfIconOpenInNew']
export const SfIconOpenSource: typeof import("@storefront-ui/vue")['SfIconOpenSource']
export const SfIconPackage: typeof import("@storefront-ui/vue")['SfIconPackage']
export const SfIconPercent: typeof import("@storefront-ui/vue")['SfIconPercent']
export const SfIconPerson: typeof import("@storefront-ui/vue")['SfIconPerson']
export const SfIconPinterest: typeof import("@storefront-ui/vue")['SfIconPinterest']
export const SfIconPublishedWithChanges: typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
export const SfIconRadioButtonChecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
export const SfIconRadioButtonUnchecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
export const SfIconReact: typeof import("@storefront-ui/vue")['SfIconReact']
export const SfIconRemove: typeof import("@storefront-ui/vue")['SfIconRemove']
export const SfIconRemoveShoppingCart: typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
export const SfIconSafetyCheck: typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
export const SfIconSchedule: typeof import("@storefront-ui/vue")['SfIconSchedule']
export const SfIconSearch: typeof import("@storefront-ui/vue")['SfIconSearch']
export const SfIconSell: typeof import("@storefront-ui/vue")['SfIconSell']
export const SfIconShare: typeof import("@storefront-ui/vue")['SfIconShare']
export const SfIconShoppingCart: typeof import("@storefront-ui/vue")['SfIconShoppingCart']
export const SfIconShoppingCartCheckout: typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
export const SfIconSort: typeof import("@storefront-ui/vue")['SfIconSort']
export const SfIconStar: typeof import("@storefront-ui/vue")['SfIconStar']
export const SfIconStarFilled: typeof import("@storefront-ui/vue")['SfIconStarFilled']
export const SfIconStarHalf: typeof import("@storefront-ui/vue")['SfIconStarHalf']
export const SfIconThumbDown: typeof import("@storefront-ui/vue")['SfIconThumbDown']
export const SfIconThumbUp: typeof import("@storefront-ui/vue")['SfIconThumbUp']
export const SfIconTune: typeof import("@storefront-ui/vue")['SfIconTune']
export const SfIconTwitter: typeof import("@storefront-ui/vue")['SfIconTwitter']
export const SfIconUndo: typeof import("@storefront-ui/vue")['SfIconUndo']
export const SfIconUnfoldMore: typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
export const SfIconUpload: typeof import("@storefront-ui/vue")['SfIconUpload']
export const SfIconViewList: typeof import("@storefront-ui/vue")['SfIconViewList']
export const SfIconVisibility: typeof import("@storefront-ui/vue")['SfIconVisibility']
export const SfIconVisibilityOff: typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
export const SfIconVsfDiamond: typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
export const SfIconVuejs: typeof import("@storefront-ui/vue")['SfIconVuejs']
export const SfIconVuestorefront: typeof import("@storefront-ui/vue")['SfIconVuestorefront']
export const SfIconWarehouse: typeof import("@storefront-ui/vue")['SfIconWarehouse']
export const SfIconWarning: typeof import("@storefront-ui/vue")['SfIconWarning']
export const SfIconYoutube: typeof import("@storefront-ui/vue")['SfIconYoutube']
export const SfInput: typeof import("@storefront-ui/vue")['SfInput']
export const SfLink: typeof import("@storefront-ui/vue")['SfLink']
export const SfListItem: typeof import("@storefront-ui/vue")['SfListItem']
export const SfLoaderCircular: typeof import("@storefront-ui/vue")['SfLoaderCircular']
export const SfLoaderLinear: typeof import("@storefront-ui/vue")['SfLoaderLinear']
export const SfModal: typeof import("@storefront-ui/vue")['SfModal']
export const SfProgressCircular: typeof import("@storefront-ui/vue")['SfProgressCircular']
export const SfProgressLinear: typeof import("@storefront-ui/vue")['SfProgressLinear']
export const SfRadio: typeof import("@storefront-ui/vue")['SfRadio']
export const SfRating: typeof import("@storefront-ui/vue")['SfRating']
export const SfRatingButton: typeof import("@storefront-ui/vue")['SfRatingButton']
export const SfScrollable: typeof import("@storefront-ui/vue")['SfScrollable']
export const SfSelect: typeof import("@storefront-ui/vue")['SfSelect']
export const SfSwitch: typeof import("@storefront-ui/vue")['SfSwitch']
export const SfTextarea: typeof import("@storefront-ui/vue")['SfTextarea']
export const SfThumbnail: typeof import("@storefront-ui/vue")['SfThumbnail']
export const SfTooltip: typeof import("@storefront-ui/vue")['SfTooltip']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyFooterNav: typeof import("../components/FooterNav.vue")['default']
export const LazyMenusLayoutNotifications: typeof import("../components/Menus/LayoutNotifications.vue")['default']
export const LazyMenusBlogbar: typeof import("../components/Menus/blogbar.vue")['default']
export const LazyMenusCharacterbar: typeof import("../components/Menus/characterbar.vue")['default']
export const LazyMenusEcosystemmenu: typeof import("../components/Menus/ecosystemmenu.vue")['default']
export const LazyMenusGamebar: typeof import("../components/Menus/gamebar.vue")['default']
export const LazyMenusLowerbar: typeof import("../components/Menus/lowerbar.vue")['default']
export const LazyMenusMonsterbar: typeof import("../components/Menus/monsterbar.vue")['default']
export const LazyMenusMythologybar: typeof import("../components/Menus/mythologybar.vue")['default']
export const LazyMenusStorybar: typeof import("../components/Menus/storybar.vue")['default']
export const LazyRelatedCharacter: typeof import("../components/Related/character.vue")['default']
export const LazyRelatedItem: typeof import("../components/Related/item.vue")['default']
export const LazyRelatedPlace: typeof import("../components/Related/place.vue")['default']
export const LazyRelatedProductCard: typeof import("../components/Related/productCard.vue")['default']
export const LazyRelatedRelatedposts: typeof import("../components/Related/relatedposts.vue")['default']
export const LazyRelatedRelatedproducts: typeof import("../components/Related/relatedproducts.vue")['default']
export const LazyRelatedRelatedstories: typeof import("../components/Related/relatedstories.vue")['default']
export const LazyRelatedStory: typeof import("../components/Related/story.vue")['default']
export const LazyRelatedVideo: typeof import("../components/Related/video.vue")['default']
export const LazySearchFilters: typeof import("../components/Search/filters.vue")['default']
export const LazySearchResultsBooksSearch: typeof import("../components/Search/results/booksSearch.vue")['default']
export const LazySearchResultsFinanceSearch: typeof import("../components/Search/results/financeSearch.vue")['default']
export const LazySearchResultsImageSearch: typeof import("../components/Search/results/imageSearch.vue")['default']
export const LazySearchResultsMusicSearch: typeof import("../components/Search/results/musicSearch.vue")['default']
export const LazySearchResultsNewsSearch: typeof import("../components/Search/results/newsSearch.vue")['default']
export const LazySearchResultsSpaceSearch: typeof import("../components/Search/results/spaceSearch.vue")['default']
export const LazySearchResultsTravelSearch: typeof import("../components/Search/results/travelSearch.vue")['default']
export const LazySearchResultsVideoSearch: typeof import("../components/Search/results/videoSearch.vue")['default']
export const LazySearch: typeof import("../components/Search/search.vue")['default']
export const LazySearchWidgetsClearRefinements: typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
export const LazySearchWidgetsNoResults: typeof import("../components/Search/widgets/NoResults.vue")['default']
export const LazyAuthenticationLogout: typeof import("../components/authentication/logout.vue")['default']
export const LazyHomePageCharacters: typeof import("../components/homePage/characters.vue")['default']
export const LazyHomePageContentSection: typeof import("../components/homePage/contentSection.vue")['default']
export const LazyHomePageIntro: typeof import("../components/homePage/intro.vue")['default']
export const LazyHomePageMultiversebanner: typeof import("../components/homePage/multiversebanner.vue")['default']
export const LazyHomePageVideoSection: typeof import("../components/homePage/videoSection.vue")['default']
export const LazyMediaAudioPlayer: typeof import("../components/media/audio/audioPlayer.vue")['default']
export const LazyMediaLivePlayer: typeof import("../components/media/live/livePlayer.vue")['default']
export const LazyMediaVideoVideojs: typeof import("../components/media/video/videojs.vue")['default']
export const LazyPagesAliens: typeof import("../components/pages/aliens.vue")['default']
export const LazyPagesAngels: typeof import("../components/pages/angels.vue")['default']
export const LazyPagesDemons: typeof import("../components/pages/demons.vue")['default']
export const LazyPagesHumans: typeof import("../components/pages/humans.vue")['default']
export const LazyPagesItems: typeof import("../components/pages/items.vue")['default']
export const LazyPagesLevels: typeof import("../components/pages/levels.vue")['default']
export const LazyPagesMythicalcreatures: typeof import("../components/pages/mythicalcreatures.vue")['default']
export const LazyPagesOthermyths: typeof import("../components/pages/othermyths.vue")['default']
export const LazyPagesPlaces: typeof import("../components/pages/places.vue")['default']
export const LazyPagesTypes: typeof import("../components/pages/types.vue")['default']
export const LazyPartialsAddtolist: typeof import("../components/partials/addtolist.vue")['default']
export const LazyPartialsComments: typeof import("../components/partials/comments.vue")['default']
export const LazyPartialsCreateListBtn: typeof import("../components/partials/createListBtn.vue")['default']
export const LazyPartialsFollowButton: typeof import("../components/partials/followButton.vue")['default']
export const LazyPartialsListBtn: typeof import("../components/partials/listBtn.vue")['default']
export const LazyPartialsShare: typeof import("../components/partials/share.vue")['default']
export const LazyPartialsShareDialog: typeof import("../components/partials/shareDialog.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazySfAccordionItem: typeof import("@storefront-ui/vue")['SfAccordionItem']
export const LazySfBadge: typeof import("@storefront-ui/vue")['SfBadge']
export const LazySfButton: typeof import("@storefront-ui/vue")['SfButton']
export const LazySfCheckbox: typeof import("@storefront-ui/vue")['SfCheckbox']
export const LazySfChip: typeof import("@storefront-ui/vue")['SfChip']
export const LazySfCounter: typeof import("@storefront-ui/vue")['SfCounter']
export const LazySfDrawer: typeof import("@storefront-ui/vue")['SfDrawer']
export const LazySfDropdown: typeof import("@storefront-ui/vue")['SfDropdown']
export const LazySfIconAdd: typeof import("@storefront-ui/vue")['SfIconAdd']
export const LazySfIconAddShoppingCart: typeof import("@storefront-ui/vue")['SfIconAddShoppingCart']
export const LazySfIconAlokai: typeof import("@storefront-ui/vue")['SfIconAlokai']
export const LazySfIconAlokaiFull: typeof import("@storefront-ui/vue")['SfIconAlokaiFull']
export const LazySfIconArrowBack: typeof import("@storefront-ui/vue")['SfIconArrowBack']
export const LazySfIconArrowDownward: typeof import("@storefront-ui/vue")['SfIconArrowDownward']
export const LazySfIconArrowForward: typeof import("@storefront-ui/vue")['SfIconArrowForward']
export const LazySfIconArrowUpward: typeof import("@storefront-ui/vue")['SfIconArrowUpward']
export const LazySfIconBase: typeof import("@storefront-ui/vue")['SfIconBase']
export const LazySfIconBlock: typeof import("@storefront-ui/vue")['SfIconBlock']
export const LazySfIconCalendarToday: typeof import("@storefront-ui/vue")['SfIconCalendarToday']
export const LazySfIconCall: typeof import("@storefront-ui/vue")['SfIconCall']
export const LazySfIconCancel: typeof import("@storefront-ui/vue")['SfIconCancel']
export const LazySfIconCheck: typeof import("@storefront-ui/vue")['SfIconCheck']
export const LazySfIconCheckBox: typeof import("@storefront-ui/vue")['SfIconCheckBox']
export const LazySfIconCheckBoxOutlineBlank: typeof import("@storefront-ui/vue")['SfIconCheckBoxOutlineBlank']
export const LazySfIconCheckCircle: typeof import("@storefront-ui/vue")['SfIconCheckCircle']
export const LazySfIconChevronLeft: typeof import("@storefront-ui/vue")['SfIconChevronLeft']
export const LazySfIconChevronRight: typeof import("@storefront-ui/vue")['SfIconChevronRight']
export const LazySfIconCircle: typeof import("@storefront-ui/vue")['SfIconCircle']
export const LazySfIconClose: typeof import("@storefront-ui/vue")['SfIconClose']
export const LazySfIconCloseSm: typeof import("@storefront-ui/vue")['SfIconCloseSm']
export const LazySfIconCompareArrows: typeof import("@storefront-ui/vue")['SfIconCompareArrows']
export const LazySfIconContactSupport: typeof import("@storefront-ui/vue")['SfIconContactSupport']
export const LazySfIconCreditCard: typeof import("@storefront-ui/vue")['SfIconCreditCard']
export const LazySfIconDelete: typeof import("@storefront-ui/vue")['SfIconDelete']
export const LazySfIconDownload: typeof import("@storefront-ui/vue")['SfIconDownload']
export const LazySfIconEmail: typeof import("@storefront-ui/vue")['SfIconEmail']
export const LazySfIconError: typeof import("@storefront-ui/vue")['SfIconError']
export const LazySfIconExpandLess: typeof import("@storefront-ui/vue")['SfIconExpandLess']
export const LazySfIconExpandMore: typeof import("@storefront-ui/vue")['SfIconExpandMore']
export const LazySfIconFacebook: typeof import("@storefront-ui/vue")['SfIconFacebook']
export const LazySfIconFavorite: typeof import("@storefront-ui/vue")['SfIconFavorite']
export const LazySfIconFavoriteFilled: typeof import("@storefront-ui/vue")['SfIconFavoriteFilled']
export const LazySfIconGridView: typeof import("@storefront-ui/vue")['SfIconGridView']
export const LazySfIconHelp: typeof import("@storefront-ui/vue")['SfIconHelp']
export const LazySfIconHome: typeof import("@storefront-ui/vue")['SfIconHome']
export const LazySfIconIndeterminateCheckBox: typeof import("@storefront-ui/vue")['SfIconIndeterminateCheckBox']
export const LazySfIconInfo: typeof import("@storefront-ui/vue")['SfIconInfo']
export const LazySfIconInstagram: typeof import("@storefront-ui/vue")['SfIconInstagram']
export const LazySfIconLanguage: typeof import("@storefront-ui/vue")['SfIconLanguage']
export const LazySfIconLocalShipping: typeof import("@storefront-ui/vue")['SfIconLocalShipping']
export const LazySfIconLocalFireDepartment: typeof import("@storefront-ui/vue")['SfIconLocal_fire_department']
export const LazySfIconLocationOn: typeof import("@storefront-ui/vue")['SfIconLocationOn']
export const LazySfIconLocationOnFilled: typeof import("@storefront-ui/vue")['SfIconLocationOnFilled']
export const LazySfIconLock: typeof import("@storefront-ui/vue")['SfIconLock']
export const LazySfIconLockOpen: typeof import("@storefront-ui/vue")['SfIconLockOpen']
export const LazySfIconLogin: typeof import("@storefront-ui/vue")['SfIconLogin']
export const LazySfIconLogout: typeof import("@storefront-ui/vue")['SfIconLogout']
export const LazySfIconMenu: typeof import("@storefront-ui/vue")['SfIconMenu']
export const LazySfIconMoreHoriz: typeof import("@storefront-ui/vue")['SfIconMoreHoriz']
export const LazySfIconMoreVert: typeof import("@storefront-ui/vue")['SfIconMoreVert']
export const LazySfIconOpenInNew: typeof import("@storefront-ui/vue")['SfIconOpenInNew']
export const LazySfIconOpenSource: typeof import("@storefront-ui/vue")['SfIconOpenSource']
export const LazySfIconPackage: typeof import("@storefront-ui/vue")['SfIconPackage']
export const LazySfIconPercent: typeof import("@storefront-ui/vue")['SfIconPercent']
export const LazySfIconPerson: typeof import("@storefront-ui/vue")['SfIconPerson']
export const LazySfIconPinterest: typeof import("@storefront-ui/vue")['SfIconPinterest']
export const LazySfIconPublishedWithChanges: typeof import("@storefront-ui/vue")['SfIconPublishedWithChanges']
export const LazySfIconRadioButtonChecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonChecked']
export const LazySfIconRadioButtonUnchecked: typeof import("@storefront-ui/vue")['SfIconRadioButtonUnchecked']
export const LazySfIconReact: typeof import("@storefront-ui/vue")['SfIconReact']
export const LazySfIconRemove: typeof import("@storefront-ui/vue")['SfIconRemove']
export const LazySfIconRemoveShoppingCart: typeof import("@storefront-ui/vue")['SfIconRemoveShoppingCart']
export const LazySfIconSafetyCheck: typeof import("@storefront-ui/vue")['SfIconSafetyCheck']
export const LazySfIconSchedule: typeof import("@storefront-ui/vue")['SfIconSchedule']
export const LazySfIconSearch: typeof import("@storefront-ui/vue")['SfIconSearch']
export const LazySfIconSell: typeof import("@storefront-ui/vue")['SfIconSell']
export const LazySfIconShare: typeof import("@storefront-ui/vue")['SfIconShare']
export const LazySfIconShoppingCart: typeof import("@storefront-ui/vue")['SfIconShoppingCart']
export const LazySfIconShoppingCartCheckout: typeof import("@storefront-ui/vue")['SfIconShoppingCartCheckout']
export const LazySfIconSort: typeof import("@storefront-ui/vue")['SfIconSort']
export const LazySfIconStar: typeof import("@storefront-ui/vue")['SfIconStar']
export const LazySfIconStarFilled: typeof import("@storefront-ui/vue")['SfIconStarFilled']
export const LazySfIconStarHalf: typeof import("@storefront-ui/vue")['SfIconStarHalf']
export const LazySfIconThumbDown: typeof import("@storefront-ui/vue")['SfIconThumbDown']
export const LazySfIconThumbUp: typeof import("@storefront-ui/vue")['SfIconThumbUp']
export const LazySfIconTune: typeof import("@storefront-ui/vue")['SfIconTune']
export const LazySfIconTwitter: typeof import("@storefront-ui/vue")['SfIconTwitter']
export const LazySfIconUndo: typeof import("@storefront-ui/vue")['SfIconUndo']
export const LazySfIconUnfoldMore: typeof import("@storefront-ui/vue")['SfIconUnfoldMore']
export const LazySfIconUpload: typeof import("@storefront-ui/vue")['SfIconUpload']
export const LazySfIconViewList: typeof import("@storefront-ui/vue")['SfIconViewList']
export const LazySfIconVisibility: typeof import("@storefront-ui/vue")['SfIconVisibility']
export const LazySfIconVisibilityOff: typeof import("@storefront-ui/vue")['SfIconVisibilityOff']
export const LazySfIconVsfDiamond: typeof import("@storefront-ui/vue")['SfIconVsfDiamond']
export const LazySfIconVuejs: typeof import("@storefront-ui/vue")['SfIconVuejs']
export const LazySfIconVuestorefront: typeof import("@storefront-ui/vue")['SfIconVuestorefront']
export const LazySfIconWarehouse: typeof import("@storefront-ui/vue")['SfIconWarehouse']
export const LazySfIconWarning: typeof import("@storefront-ui/vue")['SfIconWarning']
export const LazySfIconYoutube: typeof import("@storefront-ui/vue")['SfIconYoutube']
export const LazySfInput: typeof import("@storefront-ui/vue")['SfInput']
export const LazySfLink: typeof import("@storefront-ui/vue")['SfLink']
export const LazySfListItem: typeof import("@storefront-ui/vue")['SfListItem']
export const LazySfLoaderCircular: typeof import("@storefront-ui/vue")['SfLoaderCircular']
export const LazySfLoaderLinear: typeof import("@storefront-ui/vue")['SfLoaderLinear']
export const LazySfModal: typeof import("@storefront-ui/vue")['SfModal']
export const LazySfProgressCircular: typeof import("@storefront-ui/vue")['SfProgressCircular']
export const LazySfProgressLinear: typeof import("@storefront-ui/vue")['SfProgressLinear']
export const LazySfRadio: typeof import("@storefront-ui/vue")['SfRadio']
export const LazySfRating: typeof import("@storefront-ui/vue")['SfRating']
export const LazySfRatingButton: typeof import("@storefront-ui/vue")['SfRatingButton']
export const LazySfScrollable: typeof import("@storefront-ui/vue")['SfScrollable']
export const LazySfSelect: typeof import("@storefront-ui/vue")['SfSelect']
export const LazySfSwitch: typeof import("@storefront-ui/vue")['SfSwitch']
export const LazySfTextarea: typeof import("@storefront-ui/vue")['SfTextarea']
export const LazySfThumbnail: typeof import("@storefront-ui/vue")['SfThumbnail']
export const LazySfTooltip: typeof import("@storefront-ui/vue")['SfTooltip']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
