
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'FooterNav': typeof import("../components/FooterNav.vue")['default']
    'MenusLayoutNotifications': typeof import("../components/Menus/LayoutNotifications.vue")['default']
    'MenusBlogbar': typeof import("../components/Menus/blogbar.vue")['default']
    'MenusCharacterbar': typeof import("../components/Menus/characterbar.vue")['default']
    'MenusEcosystemmenu': typeof import("../components/Menus/ecosystemmenu.vue")['default']
    'MenusGamebar': typeof import("../components/Menus/gamebar.vue")['default']
    'MenusLowerbar': typeof import("../components/Menus/lowerbar.vue")['default']
    'MenusMonsterbar': typeof import("../components/Menus/monsterbar.vue")['default']
    'MenusMythologybar': typeof import("../components/Menus/mythologybar.vue")['default']
    'MenusStorybar': typeof import("../components/Menus/storybar.vue")['default']
    'RelatedCharacter': typeof import("../components/Related/character.vue")['default']
    'RelatedItem': typeof import("../components/Related/item.vue")['default']
    'RelatedPlace': typeof import("../components/Related/place.vue")['default']
    'RelatedRelatedposts': typeof import("../components/Related/relatedposts.vue")['default']
    'RelatedRelatedproducts': typeof import("../components/Related/relatedproducts.vue")['default']
    'RelatedRelatedstories': typeof import("../components/Related/relatedstories.vue")['default']
    'RelatedStory': typeof import("../components/Related/story.vue")['default']
    'RelatedVideo': typeof import("../components/Related/video.vue")['default']
    'SearchFilters': typeof import("../components/Search/filters.vue")['default']
    'SearchResultsBooksSearch': typeof import("../components/Search/results/booksSearch.vue")['default']
    'SearchResultsFinanceSearch': typeof import("../components/Search/results/financeSearch.vue")['default']
    'SearchResultsImageSearch': typeof import("../components/Search/results/imageSearch.vue")['default']
    'SearchResultsMusicSearch': typeof import("../components/Search/results/musicSearch.vue")['default']
    'SearchResultsNewsSearch': typeof import("../components/Search/results/newsSearch.vue")['default']
    'SearchResultsSpaceSearch': typeof import("../components/Search/results/spaceSearch.vue")['default']
    'SearchResultsTravelSearch': typeof import("../components/Search/results/travelSearch.vue")['default']
    'SearchResultsVideoSearch': typeof import("../components/Search/results/videoSearch.vue")['default']
    'Search': typeof import("../components/Search/search.vue")['default']
    'SearchWidgetsClearRefinements': typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
    'SearchWidgetsNoResults': typeof import("../components/Search/widgets/NoResults.vue")['default']
    'AuthenticationLogout': typeof import("../components/authentication/logout.vue")['default']
    'HomePageCharacters': typeof import("../components/homePage/characters.vue")['default']
    'HomePageContentSection': typeof import("../components/homePage/contentSection.vue")['default']
    'HomePageIntro': typeof import("../components/homePage/intro.vue")['default']
    'HomePageMultiversebanner': typeof import("../components/homePage/multiversebanner.vue")['default']
    'HomePageVideoSection': typeof import("../components/homePage/videoSection.vue")['default']
    'MediaAudioPlayer': typeof import("../components/media/audio/audioPlayer.vue")['default']
    'MediaLivePlayer': typeof import("../components/media/live/livePlayer.vue")['default']
    'MediaVideoVideojs': typeof import("../components/media/video/videojs.vue")['default']
    'PagesAliens': typeof import("../components/pages/aliens.vue")['default']
    'PagesAngels': typeof import("../components/pages/angels.vue")['default']
    'PagesDemons': typeof import("../components/pages/demons.vue")['default']
    'PagesHumans': typeof import("../components/pages/humans.vue")['default']
    'PagesItems': typeof import("../components/pages/items.vue")['default']
    'PagesLevels': typeof import("../components/pages/levels.vue")['default']
    'PagesMythicalcreatures': typeof import("../components/pages/mythicalcreatures.vue")['default']
    'PagesOthermyths': typeof import("../components/pages/othermyths.vue")['default']
    'PagesPlaces': typeof import("../components/pages/places.vue")['default']
    'PagesTypes': typeof import("../components/pages/types.vue")['default']
    'PartialsAddtolist': typeof import("../components/partials/addtolist.vue")['default']
    'PartialsComments': typeof import("../components/partials/comments.vue")['default']
    'PartialsCreateListBtn': typeof import("../components/partials/createListBtn.vue")['default']
    'PartialsFollowButton': typeof import("../components/partials/followButton.vue")['default']
    'PartialsListBtn': typeof import("../components/partials/listBtn.vue")['default']
    'PartialsShare': typeof import("../components/partials/share.vue")['default']
    'PartialsShareDialog': typeof import("../components/partials/shareDialog.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyFooterNav': typeof import("../components/FooterNav.vue")['default']
    'LazyMenusLayoutNotifications': typeof import("../components/Menus/LayoutNotifications.vue")['default']
    'LazyMenusBlogbar': typeof import("../components/Menus/blogbar.vue")['default']
    'LazyMenusCharacterbar': typeof import("../components/Menus/characterbar.vue")['default']
    'LazyMenusEcosystemmenu': typeof import("../components/Menus/ecosystemmenu.vue")['default']
    'LazyMenusGamebar': typeof import("../components/Menus/gamebar.vue")['default']
    'LazyMenusLowerbar': typeof import("../components/Menus/lowerbar.vue")['default']
    'LazyMenusMonsterbar': typeof import("../components/Menus/monsterbar.vue")['default']
    'LazyMenusMythologybar': typeof import("../components/Menus/mythologybar.vue")['default']
    'LazyMenusStorybar': typeof import("../components/Menus/storybar.vue")['default']
    'LazyRelatedCharacter': typeof import("../components/Related/character.vue")['default']
    'LazyRelatedItem': typeof import("../components/Related/item.vue")['default']
    'LazyRelatedPlace': typeof import("../components/Related/place.vue")['default']
    'LazyRelatedRelatedposts': typeof import("../components/Related/relatedposts.vue")['default']
    'LazyRelatedRelatedproducts': typeof import("../components/Related/relatedproducts.vue")['default']
    'LazyRelatedRelatedstories': typeof import("../components/Related/relatedstories.vue")['default']
    'LazyRelatedStory': typeof import("../components/Related/story.vue")['default']
    'LazyRelatedVideo': typeof import("../components/Related/video.vue")['default']
    'LazySearchFilters': typeof import("../components/Search/filters.vue")['default']
    'LazySearchResultsBooksSearch': typeof import("../components/Search/results/booksSearch.vue")['default']
    'LazySearchResultsFinanceSearch': typeof import("../components/Search/results/financeSearch.vue")['default']
    'LazySearchResultsImageSearch': typeof import("../components/Search/results/imageSearch.vue")['default']
    'LazySearchResultsMusicSearch': typeof import("../components/Search/results/musicSearch.vue")['default']
    'LazySearchResultsNewsSearch': typeof import("../components/Search/results/newsSearch.vue")['default']
    'LazySearchResultsSpaceSearch': typeof import("../components/Search/results/spaceSearch.vue")['default']
    'LazySearchResultsTravelSearch': typeof import("../components/Search/results/travelSearch.vue")['default']
    'LazySearchResultsVideoSearch': typeof import("../components/Search/results/videoSearch.vue")['default']
    'LazySearch': typeof import("../components/Search/search.vue")['default']
    'LazySearchWidgetsClearRefinements': typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
    'LazySearchWidgetsNoResults': typeof import("../components/Search/widgets/NoResults.vue")['default']
    'LazyAuthenticationLogout': typeof import("../components/authentication/logout.vue")['default']
    'LazyHomePageCharacters': typeof import("../components/homePage/characters.vue")['default']
    'LazyHomePageContentSection': typeof import("../components/homePage/contentSection.vue")['default']
    'LazyHomePageIntro': typeof import("../components/homePage/intro.vue")['default']
    'LazyHomePageMultiversebanner': typeof import("../components/homePage/multiversebanner.vue")['default']
    'LazyHomePageVideoSection': typeof import("../components/homePage/videoSection.vue")['default']
    'LazyMediaAudioPlayer': typeof import("../components/media/audio/audioPlayer.vue")['default']
    'LazyMediaLivePlayer': typeof import("../components/media/live/livePlayer.vue")['default']
    'LazyMediaVideoVideojs': typeof import("../components/media/video/videojs.vue")['default']
    'LazyPagesAliens': typeof import("../components/pages/aliens.vue")['default']
    'LazyPagesAngels': typeof import("../components/pages/angels.vue")['default']
    'LazyPagesDemons': typeof import("../components/pages/demons.vue")['default']
    'LazyPagesHumans': typeof import("../components/pages/humans.vue")['default']
    'LazyPagesItems': typeof import("../components/pages/items.vue")['default']
    'LazyPagesLevels': typeof import("../components/pages/levels.vue")['default']
    'LazyPagesMythicalcreatures': typeof import("../components/pages/mythicalcreatures.vue")['default']
    'LazyPagesOthermyths': typeof import("../components/pages/othermyths.vue")['default']
    'LazyPagesPlaces': typeof import("../components/pages/places.vue")['default']
    'LazyPagesTypes': typeof import("../components/pages/types.vue")['default']
    'LazyPartialsAddtolist': typeof import("../components/partials/addtolist.vue")['default']
    'LazyPartialsComments': typeof import("../components/partials/comments.vue")['default']
    'LazyPartialsCreateListBtn': typeof import("../components/partials/createListBtn.vue")['default']
    'LazyPartialsFollowButton': typeof import("../components/partials/followButton.vue")['default']
    'LazyPartialsListBtn': typeof import("../components/partials/listBtn.vue")['default']
    'LazyPartialsShare': typeof import("../components/partials/share.vue")['default']
    'LazyPartialsShareDialog': typeof import("../components/partials/shareDialog.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const FooterNav: typeof import("../components/FooterNav.vue")['default']
export const MenusLayoutNotifications: typeof import("../components/Menus/LayoutNotifications.vue")['default']
export const MenusBlogbar: typeof import("../components/Menus/blogbar.vue")['default']
export const MenusCharacterbar: typeof import("../components/Menus/characterbar.vue")['default']
export const MenusEcosystemmenu: typeof import("../components/Menus/ecosystemmenu.vue")['default']
export const MenusGamebar: typeof import("../components/Menus/gamebar.vue")['default']
export const MenusLowerbar: typeof import("../components/Menus/lowerbar.vue")['default']
export const MenusMonsterbar: typeof import("../components/Menus/monsterbar.vue")['default']
export const MenusMythologybar: typeof import("../components/Menus/mythologybar.vue")['default']
export const MenusStorybar: typeof import("../components/Menus/storybar.vue")['default']
export const RelatedCharacter: typeof import("../components/Related/character.vue")['default']
export const RelatedItem: typeof import("../components/Related/item.vue")['default']
export const RelatedPlace: typeof import("../components/Related/place.vue")['default']
export const RelatedRelatedposts: typeof import("../components/Related/relatedposts.vue")['default']
export const RelatedRelatedproducts: typeof import("../components/Related/relatedproducts.vue")['default']
export const RelatedRelatedstories: typeof import("../components/Related/relatedstories.vue")['default']
export const RelatedStory: typeof import("../components/Related/story.vue")['default']
export const RelatedVideo: typeof import("../components/Related/video.vue")['default']
export const SearchFilters: typeof import("../components/Search/filters.vue")['default']
export const SearchResultsBooksSearch: typeof import("../components/Search/results/booksSearch.vue")['default']
export const SearchResultsFinanceSearch: typeof import("../components/Search/results/financeSearch.vue")['default']
export const SearchResultsImageSearch: typeof import("../components/Search/results/imageSearch.vue")['default']
export const SearchResultsMusicSearch: typeof import("../components/Search/results/musicSearch.vue")['default']
export const SearchResultsNewsSearch: typeof import("../components/Search/results/newsSearch.vue")['default']
export const SearchResultsSpaceSearch: typeof import("../components/Search/results/spaceSearch.vue")['default']
export const SearchResultsTravelSearch: typeof import("../components/Search/results/travelSearch.vue")['default']
export const SearchResultsVideoSearch: typeof import("../components/Search/results/videoSearch.vue")['default']
export const Search: typeof import("../components/Search/search.vue")['default']
export const SearchWidgetsClearRefinements: typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
export const SearchWidgetsNoResults: typeof import("../components/Search/widgets/NoResults.vue")['default']
export const AuthenticationLogout: typeof import("../components/authentication/logout.vue")['default']
export const HomePageCharacters: typeof import("../components/homePage/characters.vue")['default']
export const HomePageContentSection: typeof import("../components/homePage/contentSection.vue")['default']
export const HomePageIntro: typeof import("../components/homePage/intro.vue")['default']
export const HomePageMultiversebanner: typeof import("../components/homePage/multiversebanner.vue")['default']
export const HomePageVideoSection: typeof import("../components/homePage/videoSection.vue")['default']
export const MediaAudioPlayer: typeof import("../components/media/audio/audioPlayer.vue")['default']
export const MediaLivePlayer: typeof import("../components/media/live/livePlayer.vue")['default']
export const MediaVideoVideojs: typeof import("../components/media/video/videojs.vue")['default']
export const PagesAliens: typeof import("../components/pages/aliens.vue")['default']
export const PagesAngels: typeof import("../components/pages/angels.vue")['default']
export const PagesDemons: typeof import("../components/pages/demons.vue")['default']
export const PagesHumans: typeof import("../components/pages/humans.vue")['default']
export const PagesItems: typeof import("../components/pages/items.vue")['default']
export const PagesLevels: typeof import("../components/pages/levels.vue")['default']
export const PagesMythicalcreatures: typeof import("../components/pages/mythicalcreatures.vue")['default']
export const PagesOthermyths: typeof import("../components/pages/othermyths.vue")['default']
export const PagesPlaces: typeof import("../components/pages/places.vue")['default']
export const PagesTypes: typeof import("../components/pages/types.vue")['default']
export const PartialsAddtolist: typeof import("../components/partials/addtolist.vue")['default']
export const PartialsComments: typeof import("../components/partials/comments.vue")['default']
export const PartialsCreateListBtn: typeof import("../components/partials/createListBtn.vue")['default']
export const PartialsFollowButton: typeof import("../components/partials/followButton.vue")['default']
export const PartialsListBtn: typeof import("../components/partials/listBtn.vue")['default']
export const PartialsShare: typeof import("../components/partials/share.vue")['default']
export const PartialsShareDialog: typeof import("../components/partials/shareDialog.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyFooterNav: typeof import("../components/FooterNav.vue")['default']
export const LazyMenusLayoutNotifications: typeof import("../components/Menus/LayoutNotifications.vue")['default']
export const LazyMenusBlogbar: typeof import("../components/Menus/blogbar.vue")['default']
export const LazyMenusCharacterbar: typeof import("../components/Menus/characterbar.vue")['default']
export const LazyMenusEcosystemmenu: typeof import("../components/Menus/ecosystemmenu.vue")['default']
export const LazyMenusGamebar: typeof import("../components/Menus/gamebar.vue")['default']
export const LazyMenusLowerbar: typeof import("../components/Menus/lowerbar.vue")['default']
export const LazyMenusMonsterbar: typeof import("../components/Menus/monsterbar.vue")['default']
export const LazyMenusMythologybar: typeof import("../components/Menus/mythologybar.vue")['default']
export const LazyMenusStorybar: typeof import("../components/Menus/storybar.vue")['default']
export const LazyRelatedCharacter: typeof import("../components/Related/character.vue")['default']
export const LazyRelatedItem: typeof import("../components/Related/item.vue")['default']
export const LazyRelatedPlace: typeof import("../components/Related/place.vue")['default']
export const LazyRelatedRelatedposts: typeof import("../components/Related/relatedposts.vue")['default']
export const LazyRelatedRelatedproducts: typeof import("../components/Related/relatedproducts.vue")['default']
export const LazyRelatedRelatedstories: typeof import("../components/Related/relatedstories.vue")['default']
export const LazyRelatedStory: typeof import("../components/Related/story.vue")['default']
export const LazyRelatedVideo: typeof import("../components/Related/video.vue")['default']
export const LazySearchFilters: typeof import("../components/Search/filters.vue")['default']
export const LazySearchResultsBooksSearch: typeof import("../components/Search/results/booksSearch.vue")['default']
export const LazySearchResultsFinanceSearch: typeof import("../components/Search/results/financeSearch.vue")['default']
export const LazySearchResultsImageSearch: typeof import("../components/Search/results/imageSearch.vue")['default']
export const LazySearchResultsMusicSearch: typeof import("../components/Search/results/musicSearch.vue")['default']
export const LazySearchResultsNewsSearch: typeof import("../components/Search/results/newsSearch.vue")['default']
export const LazySearchResultsSpaceSearch: typeof import("../components/Search/results/spaceSearch.vue")['default']
export const LazySearchResultsTravelSearch: typeof import("../components/Search/results/travelSearch.vue")['default']
export const LazySearchResultsVideoSearch: typeof import("../components/Search/results/videoSearch.vue")['default']
export const LazySearch: typeof import("../components/Search/search.vue")['default']
export const LazySearchWidgetsClearRefinements: typeof import("../components/Search/widgets/ClearRefinements.vue")['default']
export const LazySearchWidgetsNoResults: typeof import("../components/Search/widgets/NoResults.vue")['default']
export const LazyAuthenticationLogout: typeof import("../components/authentication/logout.vue")['default']
export const LazyHomePageCharacters: typeof import("../components/homePage/characters.vue")['default']
export const LazyHomePageContentSection: typeof import("../components/homePage/contentSection.vue")['default']
export const LazyHomePageIntro: typeof import("../components/homePage/intro.vue")['default']
export const LazyHomePageMultiversebanner: typeof import("../components/homePage/multiversebanner.vue")['default']
export const LazyHomePageVideoSection: typeof import("../components/homePage/videoSection.vue")['default']
export const LazyMediaAudioPlayer: typeof import("../components/media/audio/audioPlayer.vue")['default']
export const LazyMediaLivePlayer: typeof import("../components/media/live/livePlayer.vue")['default']
export const LazyMediaVideoVideojs: typeof import("../components/media/video/videojs.vue")['default']
export const LazyPagesAliens: typeof import("../components/pages/aliens.vue")['default']
export const LazyPagesAngels: typeof import("../components/pages/angels.vue")['default']
export const LazyPagesDemons: typeof import("../components/pages/demons.vue")['default']
export const LazyPagesHumans: typeof import("../components/pages/humans.vue")['default']
export const LazyPagesItems: typeof import("../components/pages/items.vue")['default']
export const LazyPagesLevels: typeof import("../components/pages/levels.vue")['default']
export const LazyPagesMythicalcreatures: typeof import("../components/pages/mythicalcreatures.vue")['default']
export const LazyPagesOthermyths: typeof import("../components/pages/othermyths.vue")['default']
export const LazyPagesPlaces: typeof import("../components/pages/places.vue")['default']
export const LazyPagesTypes: typeof import("../components/pages/types.vue")['default']
export const LazyPartialsAddtolist: typeof import("../components/partials/addtolist.vue")['default']
export const LazyPartialsComments: typeof import("../components/partials/comments.vue")['default']
export const LazyPartialsCreateListBtn: typeof import("../components/partials/createListBtn.vue")['default']
export const LazyPartialsFollowButton: typeof import("../components/partials/followButton.vue")['default']
export const LazyPartialsListBtn: typeof import("../components/partials/listBtn.vue")['default']
export const LazyPartialsShare: typeof import("../components/partials/share.vue")['default']
export const LazyPartialsShareDialog: typeof import("../components/partials/shareDialog.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
